name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Xcode
      run: |
        xcodebuild build -project ./CPR2U/CPR2U.xcodeproj -scheme CPR2U -destination "platform=iOS Simulator,name=iPhone 14,OS=latest"
